//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_ATP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderData
    {
        public int Id { get; set; }
        public int Order_Id { get; set; }
        public int Book_Id { get; set; }
        public int QuantityOrdered { get; set; }
        public double Subtotal { get; set; }
        public double ActualPrice { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
